# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6563090b7bcdcab377621207c3090fc1af01526266d6cd181abc93bf0ed033c822debdab2a6a4acfc2859dc884fc46df754ae1adb1c01e3fc1d837248af8d7f5

test:
  secret_key_base: 1ab99ba6b030c2f2feb5a6503bb500b4b3be067b20516652674195f9cf4fe7c69200aed22d5d9870867d78e6cd84edd4788d2702cd1f5ec3caf3f8aab8c7ab6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
